### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#150]
https://github.com/EpistasisLab/pmlb/blob/d79bef5d4a822c2c0fde565dac22870399a1c890/datasets/adult/metadata.yaml#L5

the source links to http://mlr.cs.umass.edu/ml/datasets/Adult which is dead

**Comment by trangdata** [comment]
Link rots are not fun 😭   I found this UCI link instead: https://archive.ics.uci.edu/ml/datasets/adult still unsure if the umass link is still out there somewhere.
