### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#151]
https://github.com/EpistasisLab/pmlb/blob/d79bef5d4a822c2c0fde565dac22870399a1c890/datasets/1089_USCrime/metadata.yaml#L9

**Comment by trangdata** [comment]
There was a [paper](https://dl.acm.org/doi/10.5555/1876210.1876216) on TunedIT.org, but the [Tunedit twitter account](https://twitter.com/TunedIT) was last active in 2014. I'm not sure if the [current site](TunedIT.org) is the same. 

The other link that was linked to from [openml](https://www.openml.org/d/1089) (http://lib.stat.cmu.edu/DASL/Datafiles/USCrime.html) is also rotten, but it did lead to an interesting source of datasets: https://dasl.datadescription.com/datafiles/.

I think we should just keep the openml link for now.
