### ISSUE TITLE
titanic and banana should be classification, not regression

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#162]
titanic (related to #21 ) should be survival yes/no

banana is also a classification problem

**Comment by trangdata** [comment]
@alexzwanenburg has resolved this issue in #165 and #166! 🚀

**Comment by lacava** [comment]
thanks @alexzwanenburg !

**Comment by hengzhe-zhang** [comment]
Great work! I guess SRBench should also be changed? @lacava
