### ISSUE TITLE
repeat dataset: promoters

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#19]
pretty sure the [promoters](https://github.com/EpistasisLab/penn-ml-benchmarks/tree/master/datasets/classification/promoters) dataset and [molecular-biology-promoters](https://github.com/EpistasisLab/penn-ml-benchmarks/tree/master/datasets/classification/molecular-biology_promoters) datasets are clones. 

```
In [1]: import pandas as pd

In [2]: from pmlb import fetch_data

In [3]: df1 = fetch_data('promoters')

In [4]: df2 = fetch_data('molecular-biology_promoters')

In [6]: from pandas.util import hash_pandas_object

In [7]: import hashlib

In [8]: rowHashes1 = hash_pandas_object(df1).values

In [9]: hash1 = hashlib.sha256(rowHashes1).hexdigest()

In [10]: rowHashes2 = hash_pandas_object(df2).values

In [11]: hash2 = hashlib.sha256(rowHashes2).hexdigest()

In [12]: hash1
Out[12]: '37c2d79bd3ecaff76ab53f3f20742245e56a3ccb1354b5c45ea4a4429afff261'

In [13]: hash2
Out[13]: '37c2d79bd3ecaff76ab53f3f20742245e56a3ccb1354b5c45ea4a4429afff261'

In [14]: hash1==hash2
Out[14]: True

```

**Comment by trangdata** [comment]
Also, looks like column `name` is the row id and should be removed. I vote that we keep `promoters` and remove the column `name` from it.

**Comment by trangdata** [comment]
I believe this has been addressed [here](https://github.com/EpistasisLab/penn-ml-benchmarks/commit/223569e1150ef3684d7c27bd15d05345fec42f9c).
