### ISSUE TITLE
continuous integration for summary statistics and readme data

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#24]
At the moment the summary stats and readme files need to be generated manually. 

- [x] Based on our discussion, let's move this to a CI step so that users can more easily contribute datasets/dataset metadata without having to rerun those scripts. 
- [x] Use the CI to issue some basic checks on their metadata.yaml file to make sure it's the proper format.

**Comment by lacava** [comment]
some basic metadata checks:

- [ ] all elements of schema are present
- [ ] dataset hash ids should be unique 
- [ ] legal values for things like feature type

**Comment by weixuanfu** [comment]
I added CI into PMLB2.0 branch with 2 unit tests for checking metadata of a example (discussed in #22). The [1st CI build](https://travis-ci.org/github/EpistasisLab/penn-ml-benchmarks/builds/683861678) was failed due to due to a error in installation step and [the 2nd one](https://travis-ci.org/github/EpistasisLab/penn-ml-benchmarks/builds/683862813) passed without error.

**Comment by lacava** [comment]
since this is now handled by pandas profiling in CI, i'm closing this issue.

**Comment by weixuanfu** [comment]
Scenario 1 dataset.tsv.gz changed/updated without metadata.yaml
 - auto-generate metadata.yaml, readme and summary_stats.csv, pandas_profiling

Scenario 2 dataset.tsv.gz changed/updated with metadata.yaml (
 - auto-generate readme and summary_stats.csv, pandas_profiling

Scenario 3 only update metadata.yaml
 - do nothing?

**Comment by trangdata** [comment]
I think we should separate `get_updated_datasets()` and `get_updated_metadatas()`.

1. Contributor adds a new dataset. When the PR is submitted:
- `get_updated_datasets()` picks up this new dataset. CI autogenerates metadata.yaml, readme.md, summary_stats.tsv, all_summary_stats.tsv, pandas profiling, and updates `dataset_names` (and `classification_dataset_names` and `regression_dataset_names`, if we keep these variables).
- A reviewer asks the contributor to manually update the metadata.yaml.
- CI adds the dataset name to `datasets_with_metadata`.
- Merge.


2. Contributor comes in and contributes to a metadata.yaml file. Let's assume that the inferred "task" is incorrect and contributor fixes this.
- `get_updated_metadatas()` picks up this new dataset. 
- CI regenerates summary_stats.tsv, updates `classification_dataset_names` and `regression_dataset_names`, and adds the dataset name to `dataset_with_metadata`. 
- Merge.

**Comment by trangdata** [comment]
Closed by #110 and #111.
