### ISSUE TITLE
Standardize names

### ISSUE THREAD

**Issue by trangdata** [EpistasisLab/pmlb#28]
As @lacava suggested in #22, couple TODO items:

- [ ] rename the datasets and feature names so that special characters, when possible, are replaced with `_`. Replace uppercase letters with lowercase letters.

- [ ] In addition, I think we should move all datasets one level up and remove the subdirectory `classification` and `regression` because this information is already in metadata to do before generating `metadata.yaml` files, unless this breaks too many things.

**Comment by weixuanfu** [comment]
I have concerns about renaming feature names because it may cause some misunderstandings when users try to check raw data from original source. 

For example, the [audit](https://www.openml.org/d/179) dataset in OpenML was kept "-" instead of "_" in feature names.

**Comment by trangdata** [comment]
> For example, the audit dataset in OpenML was kept "-" instead of "_" in feature names.

I understand the original source may have a different format, but if we want our datasets to be uniform, we'll have to make some changes. If the map back to the original source is not clear, we can document it. Nevertheless, I'm okay with keeping the feature name as is for the moment.
