### ISSUE TITLE
Use Git LFS

### ISSUE THREAD

**Issue by trangdata** [EpistasisLab/pmlb#30]
It’s not too urgent but I think it might be good to utilize Git LFS and allow for larger datasets to be added. More [here](https://stackoverflow.com/questions/35575400/what-is-the-advantage-of-git-lfs).

Users who want to download the whole resource can still do that with git clone, but they'll need git LFS [installed and set up](https://git-lfs.github.com/) for their user account, or they can download the zip file from GitHub. We can add this information to the README.

Later, we can save all the changes in one branch and, in an active branch (master branch when all this gets merged), we can squash all the old commits to reduce the repo space.

**Comment by JDRomano2** [comment]
It looks like LFS support was added by e447f5657e001e73642756b664ea1421408aa967 and a7f3f89291fee80751ff1befd01068088f501671. Can this be closed, or is there still work to do before LFS is 'fully' supported?

**Comment by trangdata** [comment]
Yes. I think we can close this now.
