### ISSUE TITLE
move datasets to one folder?

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#31]
commit 469bfb2932cd0755d9ca89dd80f6af81d6312d48 has the wine quality dataset in the datasets/ folder. as [discussed here](https://github.com/EpistasisLab/penn-ml-benchmarks/commit/0fbca9ca796517711ca89f34e57fc6228f10f9ef#commitcomment-39253437) because we have metadata defining tasks now, we could move all datasets to one folder instead of separate regression and classification folders.

**Comment by trangdata** [comment]
Second TODO task in #28.
