### ISSUE TITLE
update README for PMLB2

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#34]
For PMLB2.0, we are capturing metadata in metadata.yaml and summary stats in a csv file. So, the readme is now free to present other info. Brainstorming what would be useful in there:

- [x] links to the metadata and summary data
- [x] plot of distribution of target
- [x] some summary info, like rows, cols, nclasses
- [x] for appropriately sized datasets, pairwise plots of the columns would be nice, maybe for the top 10 features

Just some ideas

**Comment by lacava** [comment]
this work is now on the https://github.com/EpistasisLab/penn-ml-benchmarks/tree/readme_update_34 branch

**Comment by lacava** [comment]
we should move this to a github action so that newly added datasets have READMEs automatically generated.

**Comment by trangdata** [comment]
This has been completed [here](https://github.com/EpistasisLab/penn-ml-benchmarks/pull/80/commits/b55bcbeaa84ae99b60b9f99599b891b84f240412).
