### ISSUE TITLE
v0.3.1 minor release

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pmlb#35]
- [x] warning for updating pmlb after August (?) and pmlb <=0.3 won't be support any more after the date
- [x] add new links for datasets in future version of pmlb.

**Comment by lacava** [comment]
>  warning for updating pmlb after August (?) and pmlb <=0.3 won't be support any more after the date

August feels like a long time. How about 2 weeks? Too fast?

**Comment by weixuanfu** [comment]
Ha, I did not add any time in the warning message.
