### ISSUE TITLE
Get categorical features

### ISSUE THREAD

**Issue by cmougan** [EpistasisLab/pmlb#37]
Hi! I am trying to use penn-ml-benchmarks to test encodings of categorical features.
Right now I am using "get_types ()" but it returns that all are categorical

```
for regression_dataset in regression_dataset_names:

    X, y = fetch_data(regression_dataset, return_X_y=True,local_cache_dir='./results_regression/datasets/')
    
    X = pd.DataFrame(X)
    y = pd.DataFrame(y)
    print(set(get_types(X)))

```

Is there a way to get the categorical features of the datasets?

**Comment by lacava** [comment]
hi @cmougan, we rely on pandas for determining the data type in `get_types`. I am guessing that the regression datasets may all be normalized and therefore read in as continuous. @weixuanfu, is this true? For classification datasets this is not the case:

```
for classification_dataset in classification_dataset_names: 
    df = fetch_data(classification_dataset) 
    print(set(get_types(df))) 
                                                                   
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'continous', 'binary'}
{'continous', 'binary'}
{'continous', 'binary', 'discrete'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'binary'}
{'discrete', 'continous', 'binary'}
{'continous', 'binary', 'discrete'}
{'continous', 'discrete'}
{'discrete', 'continous', 'binary'}
{'discrete', 'binary'}
etc..
```

but @cmougan to answer your question, you may do something like this:

```
def get_types_adhoc(df): 
    types = [] 
    for col in df.columns: 
        if df[col].nunique()<5: 
             types.append('categorical') 
        else: 
            types.append('continuous') 
    return types 
         
for regression_dataset in regression_dataset_names: 
    df = fetch_data(regression_dataset) 
 print(set(get_types_adhoc(df))) 
{'continuous'}
{'categorical'}
{'continuous'}
{'continuous'}
{'continuous', 'categorical'}
{'continuous', 'categorical'}
etc
```

depends on how you want to define categorical. @weixuanfu @trang1618 we should look into how the regression datasets are getting preprocessed.

**Comment by lacava** [comment]
by the way, '5' is probably not the right cutoff for categorical, so adjust it to whatever definition works for you.

**Comment by weixuanfu** [comment]
@lacava no normalization was applied on regression datasets But I found this is a issue for regression dataset. For example, the [cloud dataset](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/PMLB2.0/datasets/210_cloud/metadata.yaml) is from [this openml link](https://www.openml.org/d/210). In this link, the `seeded` and `season` columns should be categorical but in our current metadata, they are `continous`. The reason is that the they were encoded as float (0.0, 1.0) instead of integer (0, 1) in pmlb (see the stdout below). We might need recode them as integer to let pandas for determining the right data type.
```shell
seeded	season	NC	SC	NWC	target
0.0	0.0	1.649999976158142	1.7999999523162842	3.3299999237060547	1.690000057220459
1.0	0.0	1.090000033378601	0.7900000214576721	1.590000033378601	0.7400000095367432
0.0	1.0	2.390000104904175	0.36000001430511475	2.059999942779541	0.8100000023841858
1.0	1.0	2.9600000381469727	1.2699999809265137	4.050000190734863	1.440000057220459
0.0	1.0	4.159999847412109	2.1600000858306885	6.0	2.4800000190734863
1.0	1.0	2.759999990463257	0.8700000047683716	4.170000076293945	0.8399999737739563
1.0	1.0	1.0800000429153442	0.8500000238418579	3.450000047683716	0.3700000047683716
0.0	1.0	0.25999999046325684	0.4699999988079071	0.8999999761581421	0.3700000047683716
1.0	2.0	2.5299999713897705	1.0800000429153442	3.6500000953674316	1.3300000429153442
```
