### ISSUE TITLE
Add regression benchmark

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/pmlb#6]
@weixuanfu2016 is working on adding regression datasets to PMLB. Please report on your progress here, @weixuanfu2016.

**Comment by weixuanfu** [comment]
Ok will do:-)

**Comment by weixuanfu** [comment]
I tried to convert those regression data to tsv file in pmlb But I did not merge them into pmlb repo yet. I found a few dataset is very huge, like >200Mb in tsv format. You can check them in the LPC path I sent over in slack. Should we exclude them?

Another issue with pmlb. The target name of all current classification benchmarks in pmlb is `class`, I think it is not good for regression benchmark so I used `pmlb_reg_target` instead, is it OK?

**Comment by rhiever** [comment]
How big are the files when gzipped?

Let's call the `class` equivalent as `target`.

**Comment by weixuanfu** [comment]
Even gzip file is more than 110Mb. It is a benchmark with 1 million samples.

`target` sounds good

**Comment by rhiever** [comment]
We might end up changing the PMLB standard such that all target columns are named `target`.

**Comment by lacava** [comment]
if you want i can add a collection of benchmark problems used in GP (mostly synthetic).

**Comment by weixuanfu** [comment]
@lacava sounds good.

**Comment by rhiever** [comment]
Sure @lacava, send over a PR and describe them for us. 👍

**Comment by lacava** [comment]
i was thinking it would also be nice to have a notebook for generating the synthetic datasets, for example for the korns / keijzer / pagie problems. where should that go?

**Comment by rhiever** [comment]
Maybe that would be a separate project, unless we were explicitly creating datasets to upload to PMLB.

**Comment by lacava** [comment]
yea, they would correspond to datasets in the archive.

**Comment by rhiever** [comment]
Cool, send a separate PR for it and we'll take a look. :-)

**Comment by rhiever** [comment]
@weixuanfu, can you please re-send the PR with the regression benchmarks? Please take care when moving the existing classification datasets around.

**Comment by weixuanfu** [comment]
OK, will do

**Comment by weixuanfu** [comment]
Please check PR #15
