### ISSUE TITLE
Issues about deployment step

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pmlb#63]
After some tests in Github, our current deployment step works only on pull requests from a branch in this repo but does not work with a branch in a forked repo. Also somehow the deployment step failed in `git push`. 

Additionally, I think the right behavior should be that deployment step only run if a pull request or commit is merged into PMLB2.0 or master branch.

I will check on it next week.

**Comment by trangdata** [comment]
I just opened an issue [here](https://github.com/peaceiris/actions-gh-pages/issues/358).

**Comment by trangdata** [comment]
This has now been resolved in v1.0 release.
