### ISSUE TITLE
GitHub Pages for PMLB

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pmlb#64]
Enable GitHub Pages for better documentation.

**Comment by weixuanfu** [comment]
Example website: https://epistasislab.github.io/penn-ml-benchmarks/

**Comment by trangdata** [comment]
Looks great! I'm curious why some python code block does not render correctly (e.g. https://epistasislab.github.io/penn-ml-benchmarks/how-to-verify-source/)

**Comment by weixuanfu** [comment]
Hmm it seems that `mkdocs` do not support indents for code block. I removed indents before code blocks in markdown file and then rebuild the page.

**Comment by weixuanfu** [comment]
To do for dataset summary: https://matteoguzzo.com/blog/embed-html-graphs-plotly

**Comment by trangdata** [comment]
> To do for dataset summary: https://matteoguzzo.com/blog/embed-html-graphs-plotly

A plotly figure was generated [here](https://github.com/EpistasisLab/penn-ml-benchmarks/pull/74/commits/db4e848226d020030485880cf3229024306fc640).

**Comment by trangdata** [comment]
@JDRomano2 volunteered to add a documentation page, but I'll close this and open a separate issue.
