### ISSUE TITLE
cars and cars1 are very similar

### ISSUE THREAD

**Issue by praneelc** [EpistasisLab/pmlb#85]
car and cars 1 are very similar; all datapoint appear to be the same, excepting that cars has 1 additional feature, brand. Since the datasets are the same cars1 just has one less column, it might make sense to get rid of cars1 altogether and just keep cars

**Comment by trangdata** [comment]
Confirm [here](https://colab.research.google.com/drive/1hxDSxCRy7rBMKvTPTLAObDRSUxDNP9hw?usp=sharing). Will remove `cars1`.

**Comment by trangdata** [comment]
Addressed by #113.
