### ISSUE TITLE
Add fetch_dateset_list function to filter datasets based on criteria

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pmlb#87]
Add fetch_dateset_list for filter datasets based on criteria (like sample size, feature numbers or similarity based on KNN distance among datasets.

**Comment by trangdata** [comment]
How about a different name like `select_datasets()` or `filter_datasets()`?

**Comment by weixuanfu** [comment]
Prefer `select_datasets()`

**Comment by trangdata** [comment]
@praneelc expressed that he would like to help with this.

**Comment by trangdata** [comment]
Closed by #135.
