### ISSUE TITLE
Include metafeatures & evaluation results

### ISSUE THREAD

**Issue by ghost** [EpistasisLab/pmlb#9]
Not sure if this already included, but would it be possible to include the metafeatures and performance results described in the paper? (would be really handy for algorithm selection research).

**Comment by rhiever** [comment]
Most of the work for the PMLB paper is over in [this](https://github.com/rhiever/sklearn-benchmarks) repo. This repo is more for managing and distributing the datasets. We haven't quite cleaned that other repo up yet, though, as we're working on another follow-up paper based on the data.

**Comment by lacava** [comment]
would be good to have a metadata file for each dataset that gave the data types (continuous, categorical, binary etc.) for each feature.

**Comment by trangdata** [comment]
> would be good to have a metadata file for each dataset that gave the data types (continuous, categorical, binary etc.) for each feature.

[PMLB v1.0](https://github.com/EpistasisLab/penn-ml-benchmarks/releases/tag/v1.0.1.post3) now has metadata file for each dataset.
