### ISSUE TITLE
Add documentation page

### ISSUE THREAD

**Issue by trangdata** [EpistasisLab/pmlb#90]
I think a brief documentation page of the core functions of pmlb would be helpful.

**Comment by JDRomano2** [comment]
Ideally, we'd have API docs that automatically compile from the code's docstrings every time the docs pages update. This is a bit nontrivial without migrating the entire documentation to Sphinx (or equivalent) with auto-doc capabilities.

In the meantime, I'm building a static API Docs page that will suffice for now. PMLB only has a few user-facing functions, so this really isn't a bad compromise for the time being.

**Comment by trangdata** [comment]
I agree. I don't envision the pmlb functions changing that much in the future. Most changes would be coming from existing and new datasets. Static Docs suffice for now.

**Comment by lacava** [comment]
there will probably be a few new functions added in the next couple months, but other than that I agree.
