### ISSUE TITLE
molecular_biology_promoters issues

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pmlb#91]
- [x] instance still appears in the [pandas profiling report](https://epistasislab.github.io/penn-ml-benchmarks/profile/molecular_biology_promoters.html#interactions)
- [ ] target description is wrong; 0 corresponds to promoters. these labels might need to be flipped to match source.

**Comment by trangdata** [comment]
> instance still appears in the pandas profiling report

You can see the updated report currently on gh-pages [here](https://htmlpreview.github.io/?https://github.com/EpistasisLab/penn-ml-benchmarks/blob/gh-pages/profile/molecular_biology_promoters.html). Even though everything was deployed correctly, the site is not being built. I think we have reached the repo size limits.

![site-build-error](https://user-images.githubusercontent.com/1679452/90533776-f275fb00-e146-11ea-88ab-b283669fb81b.png)

I'll troubleshoot this, but I think we need to think long term about tracking with LFS and other ways to reduce the repo size.

> target description is wrong; 0 corresponds to promoters. these labels might need to be flipped to match source.

Did you mean [this](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/223569e1150ef3684d7c27bd15d05345fec42f9c/datasets/molecular_biology_promoters/metadata.yaml#L92)? Isn't this correct?

**Comment by lacava** [comment]
> description: Positive class indicates a promoter.
>  code: -:1, +:0 (promoter)

In PMLB, 0 indicates a promoter. In the original data, class labels were (+,-), with + indicating promoter. It seems more in line with that encoding to have "1" indicate a promoter. In either case the description in the metadata is wrong, positive class in PMLB indicates NOT a promoter.

**Comment by trangdata** [comment]
Hmm not sure if I'm missing something completely here...

Currently, in PMLB, `0 = + = promoter` (both metadata and data).
In the original data, `+ = promoter`.

I agree it's more conventional to encode 1 as promoter. We can flip that. But I don't think what we have currently is wrong.

**Comment by lacava** [comment]
The description in metadata.yaml reads "Positive class indicates promoter". While this is true for the source data, for the PMLB data, 0 indicates promoter. So I'm suggesting we update the description.

**Comment by trangdata** [comment]
Ah, I read this "positive" as literal "+". Let's go ahead and recode the target then.
